# Clé unique du projet (donnée par SonarCloud)
sonar.projectKey=Ngokeng-Rayan_todoapp
# Clé de ton organisation (donnée par SonarCloud)
sonar.organization=ngokeng-rayan
# Nom du projet affiché dans SonarQube
sonar.projectName=Kaba-Delivery (To-Do App)
# Version du projet
sonar.projectVersion=1.0

# Chemin vers les sources (le dossier courant)
sonar.sources=.

# Exclure les dossiers inutiles de l'analyse
sonar.exclusions=venv/**,env/**,**/migrations/**,**/*.html,**/*.css,**/*.js

# Spécifier le langage principal
sonar.language=py

# Encodage
sonar.sourceEncoding=UTF-8
